"""add password_hash to users

Revision ID: 28312187df60
Revises: 4f66abbf07f6
Create Date: 2021-04-14 20:36:02.821999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28312187df60'
down_revision = '4f66abbf07f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
